
#Format: [["dimension_1", temperature1, *units], ["dimension_2", temperature2, *units]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [["minecraft:the_nether", 0.7], ["minecraft:the_end", -0.1]]
	#Defines the temperature of a dimension, overriding all other biome and dimension temperatures/settings
	"Dimension Temperatures" = []

#Format: [["biome_1", <low-temp>, <high-temp>, <*units>], ["biome_2", <low-temp>, <high-temp>, <*units>]... etc]
#low-temp: The temperature of the biome at midnight
#high-temp: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
[Biomes]
	#Applies an offset to the temperature of a biome
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding the biome's default temperature
	"Biome Temperatures" = [["minecraft:soul_sand_valley", 53, 53, "F"], ["minecraft:old_growth_birch_forest", 58, 72, "F"], ["minecraft:river", 60, 70, "F"], ["minecraft:swamp", 72, 84, "F"], ["minecraft:savanna", 70, 95, "F"], ["minecraft:savanna_plateau", 76, 98, "F"], ["minecraft:windswept_savanna", 67, 90, "F"], ["minecraft:taiga", 44, 62, "F"], ["minecraft:snowy_taiga", 19, 48, "F"], ["minecraft:old_growth_pine_taiga", 48, 62, "F"], ["minecraft:old_growth_spruce_taiga", 48, 62, "F"], ["minecraft:desert", 48, 115, "F"], ["minecraft:stony_shore", 50, 64, "F"], ["minecraft:snowy_beach", 38, 52, "F"], ["minecraft:snowy_slopes", 24, 38, "F"], ["minecraft:windswept_forest", 48, 66, "F"], ["minecraft:frozen_peaks", 15, 33, "F"], ["minecraft:warm_ocean", 67, 76, "F"], ["minecraft:deep_frozen_ocean", 56, 65, "F"], ["minecraft:jungle", 76, 87, "F"], ["minecraft:bamboo_jungle", 76, 87, "F"], ["minecraft:badlands", 84, 120, "F"], ["minecraft:wooded_badlands", 80, 108, "F"], ["minecraft:eroded_badlands", 88, 120, "F"], ["minecraft:deep_dark", 63, 63, "F"]]

[Blocks]
	# Format:
	# [["block-ids", <temperature>, <range>, <*units>, <*max effect>, <*predicates>, <*nbt>, <*temperature-limit>], [etc...], [etc...]]
	# * = Optional
	# 
	# Arguments:
	# block-ids: Multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	# temperature: The temperature of the block, in Minecraft units
	# *falloff: The block is less effective as distance increases
	# *max effect: The maximum temperature change this block can cause to a player (even with multiple blocks)
	# *predicates: The state that the block has to be in for the temperature to be applied (i.e. lit=true).
	# - (Multiple predicates can be used by separating them with commas [i.e. "lit=true,waterlogged=false"])
	# *nbt: The NBT data that the block must have for the temperature to be applied.
	# *temperature-limit: The maximum world temperature at which this block temp will be effective.
	# - (Represents the minimum temp if the block temp is negative)
	"Block Temperatures" = [["cold_sweat:boiler", 0.27, 7, "mc", 0.88, "lit=true", "", 4], ["cold_sweat:icebox", -0.27, 7, "mc", 0.88, "frosted=true", "", 0], ["minecraft:fire", 0.476, 7, "mc", 0.9, "", "", 8], ["#minecraft:campfires", 0.476, 7, "mc", 0.9, "lit=true", " ", 8], ["minecraft:magma_block", 0.25, 3, "mc", 1.0], ["minecraft:lava_cauldron", 0.5, 7, "mc", 1.5], ["minecraft:ice", -0.15, 4, "mc", 0.6, "", "", -0.7], ["minecraft:packed_ice", -0.25, 4, "mc", 1.0, "", "", -0.7], ["minecraft:blue_ice", -0.35, 4, "mc", 1.4, "", "", -0.7], ["#minecraft:ice", -0.15, 4, "mc", 0.6, "", "", -0.7]]
	#The maximum range of blocks' area of effect
	#Note: This will not change anything unless blocks are configured to utilize the expanded range
	#This value is capped at 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 7
	#When set to true, uses Cold Sweat's temperature system to determine water freezing behavior
	"Custom Freezing Behavior" = true
	#When set to true, modifies ice blocks to be harvestable with a pickaxe
	"Custom Ice Drops" = true

[Misc]
	#A temperature offset applied when the sky is overcast
	#Format: [offset, *units]
	"Overcast Temperature Offset" = [-0.35, "mc"]
	#Overrides the world temperature when the player is within this structure
	#Format: [["structure_1", temperature1, *units], ["structure_2", temperature2, *units]... etc]
	#(* = optional)
	"Structure Temperatures" = [["minecraft:igloo", 65, "F"]]
	#Offsets the world temperature when the player is within this structure
	#Format: [["structure_1", offset1, *units], ["structure_2", offset2, *units]... etc]
	#(* = optional)
	"Structure Temperature Offsets" = []
	#List of blocks that will allow the player to sleep on them, regardless of the "Prevent Sleep When in Danger" setting
	#Use this list if the player is not getting the temperature effect from sleeping on particular blocks
	"Sleep Check Override Blocks" = []
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Check Sleeping Conditions" = true
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

["Thermal Sources"]
	#How effective thermal sources are at normalizing temperature
	#Range: 0.0 ~ 1.0
	"Thermal Source Strength" = 0.75
	#List of additional blocks that thermal sources can spread through
	#Use this list if thermal sources aren't spreading through particular blocks that they should
	"Thermal Source Spread Whitelist" = ["cold_sweat:hearth_bottom", "minecraft:iron_bars", "minecraft:jungle_leaves", "minecraft:oak_leaves", "minecraft:spruce_leaves", "minecraft:dark_oak_leaves", "minecraft:acacia_leaves", "minecraft:birch_leaves", "minecraft:azalea_leaves", "minecraft:flowering_azalea_leaves", "minecraft:mangrove_leaves", "minecraft:cherry_leaves", "tfc:wood/leaves/acacia", "tfc:wood/leaves/ash", "tfc:wood/leaves/aspen", "tfc:wood/leaves/birch", "tfc:wood/leaves/blackwood", "tfc:wood/leaves/chestnut", "tfc:wood/leaves/douglas_fir", "tfc:wood/leaves/hickory", "tfc:wood/leaves/kapok", "tfc:wood/leaves/mangrove", "tfc:wood/leaves/maple", "tfc:wood/leaves/oak", "tfc:wood/leaves/palm", "tfc:wood/leaves/pine", "tfc:wood/leaves/rosewood", "tfc:wood/leaves/sequoia", "tfc:wood/leaves/spruce", "tfc:wood/leaves/sycamore", "tfc:wood/leaves/white_cedar", "tfc:wood/leaves/willow", "tfc:plant/cherry_leaves", "tfc:plant/green_apple_leaves", "tfc:plant/lemon_leaves", "tfc:plant/olive_leaves", "tfc:plant/orange_leaves", "tfc:plant/peach_leaves", "tfc:plant/plum_leaves", "tfc:plant/red_apple_leaves", "afc:wood/leaves/cypress", "afc:wood/leaves/tualang", "afc:wood/leaves/hevea", "afc:wood/leaves/teak", "afc:wood/leaves/eucalyptus", "afc:wood/leaves/baobab", "afc:wood/leaves/fig", "afc:wood/leaves/mahogany", "afc:wood/leaves/ironwood", "afc:wood/leaves/ipe", "afc:wood/leaves/gum_arabic", "afc:wood/leaves/acacia_koa", "afc:wood/leaves/mpingo_blackwood", "afc:wood/leaves/mountain_fir", "afc:wood/leaves/balsam_fir", "afc:wood/leaves/scrub_hickory", "afc:wood/leaves/bigleaf_maple", "afc:wood/leaves/weeping_maple", "afc:wood/leaves/black_oak", "afc:wood/leaves/live_oak", "afc:wood/leaves/stone_pine", "afc:wood/leaves/red_pine", "afc:wood/leaves/tamarack", "afc:wood/leaves/giant_rosewood", "afc:wood/leaves/coast_spruce", "afc:wood/leaves/sitka_spruce", "afc:wood/leaves/black_spruce", "afc:wood/leaves/atlas_cedar", "afc:wood/leaves/weeping_willow", "afc:wood/leaves/rainbow_eucalyptus", "afc:wood/leaves/mountain_ash", "afc:wood/leaves/weeping_cypress", "afc:wood/leaves/redcedar", "afc:wood/leaves/bald_cypress", "afc:wood/leaves/rubber_fig", "afc:wood/leaves/small_leaf_mahogany", "afc:wood/leaves/sapele_mahogany", "afc:wood/leaves/red_silk_cotton", "afc:wood/leaves/coast_redwood", "afc:wood/leaves/poplar", "afc:wood/leaves/iroko_teak", "afc:wood/leaves/flame_of_the_forest", "afc:wood/leaves/lebombo_ironwood", "afc:wood/leaves/horsetail_ironwood", "afc:wood/leaves/jaggery_palm", "ad_astra:glacian_leaves", "vinery:dark_cherry_leaves", "vinery:apple_leaves", "vinery:grapevine_leaves", "quark:blue_blossom_leaves", "quark:lavender_blossom_leaves", "quark:orange_blossom_leaves", "quark:yellow_blossom_leaves", "quark:red_blossom_leaves", "quark:ancient_leaves", "firmalife:plant/cocoa_leaves", "firmalife:plant/fig_leaves"]
	#List of additional blocks that thermal sources spread through
	#Use this list if thermal sources are spreading through particular blocks that they shouldn't
	"Thermal Source Spread Blacklist" = ["minecraft:water"]

	["Thermal Sources".Hearth]
		#Allows the hearth to automatically turn on/off based on nearby players' temperature
		#If false, it turns on/off by redstone signal instead
		"Automatic Hearth" = false
		#The distance the hearth's air will travel from a source, like the hearth itself or the end of a pipe
		#Range: > 0
		"Hearth Range" = 20
		#The maximum distance that air can be piped away from the hearth
		#Range: > 0
		"Max Hearth Range" = 96
		#The maximum volume of the hearth's area of effect
		#Range: > 1
		"Hearth Volume" = 12000
		#The time it takes for the hearth to be fully functional after being placed
		#Range: > 0
		"Hearth Warm-Up Time" = 1200
		#The maximum amount of insulation that the hearth can provide
		#Range: 0 ~ 10
		"Hearth Effect Strength" = 10

	["Thermal Sources".Boiler]
		#Allows the boiler to automatically turn on/off based on nearby players' temperature
		#If false, it turns on/off by redstone signal instead
		"Automatic Boiler" = false
		#The distance the boiler's air will travel from a source, like the boiler itself or the end of a pipe
		#Range: > 0
		"Boiler Range" = 16
		#The maximum distance that air can be piped away from the boiler
		#Range: > 0
		"Max Boiler Range" = 96
		#The maximum volume of the boiler's area of effect
		#Range: > 1
		"Boiler Volume" = 2000
		#The time it takes for the boiler to be fully functional after being placed
		#Range: > 0
		"Boiler Warm-Up Time" = 1200
		#The maximum amount of insulation that the boiler can provide
		#Range: 0 ~ 10
		"Boiler Warmth Strength" = 5

	["Thermal Sources".Icebox]
		#Allows the icebox to automatically turn on/off based on nearby players' temperature
		#If false, it turns on/off by redstone signal instead
		"Automatic Icebox" = false
		#The distance the icebox's air will travel from a source, like the icebox itself or the end of a pipe
		#Range: > 0
		"Icebox Range" = 16
		#The maximum distance that air can be piped away from the icebox
		#Range: > 0
		"Max Icebox Range" = 96
		#The maximum volume of the icebox's area of effect
		#Range: > 1
		"Icebox Volume" = 2000
		#The time it takes for the icebox to be fully functional after being placed
		#Range: > 0
		"Icebox Warm-Up Time" = 1200
		#The maximum amount of insulation that the icebox can provide
		#Range: 0 ~ 10
		"Icebox Chill Strength" = 5

