
[EventSpawnRate]
	#Determines how many times an event can occur. 24001 means one possible event a day.
	event_spawn_rate = 0.0

[EventChance]
	#The chance an event can occur. Formula: 1 / event_chance.
	event_chance = 1.0

[Events]
	#Include Acid Rain in Event Pool
	AcidRain = false
	#Include Low Gravity in Event Pool
	LowGravity = false
	#Include Artifact Hunt in Event Pool
	ArtifactHunt = false
	#Include Alien Invasion in Event Pool
	AlienInvasion = true

